### ISSUE TITLE
Incorrect Error when ContentKind contains Scope Attribute

### ISSUE THREAD

**Issue by andrewslade80** [Netflix/photon#361] opened 2024-01-18 17:26 UTC
When validating a CPL with a ContentKind element that has a Scope Attribute Photon is incorrectly reporting an error that Scope is not allowed in ContentKind.

`fcpqa@fcpqas-MacBook-Pro photon % java -cp ./build/libs/\*: com.netflix.imflibrary.st2067_2.Composition ~/Desktop/Package\ Name/CPL_PackageName_CPL.xml 
18 Jan 2024 09:24:27,668 [INFO ] [Composition]: CompositionPlaylist Document has 1 errors and 0 warnings
18 Jan 2024 09:24:27,668 [ERROR] [Composition]: ERROR-Line Number : 10 - cvc-complex-type.3.2.2: Attribute 'Scope' is not allowed to appear in element 'ContentKind'. [Photon version: 4.9.0-SNAPSHOT]`

You can see in section 6.4 of 2063-3 that the ContentKind element is clearly defined with the Scope attribute.

**Comment by fschleich** [comment] 2024-09-06 01:51
Sorry for the late response. Based on the error msg, you might have spelled "scope" with a capital "S"? I'm not able to reproduce the issue with the right spelling, so will close the issue for now.

**Closed by fschleich** 2024-09-06 01:51 UTC
