### ISSUE TITLE
IMF packages rejected by Netflix but Photon doesn't issue any errors

### ISSUE THREAD

**Issue by go4shoe** [Netflix/photon#182] opened 2017-03-09 23:03 UTC
The following package:

https://drive.google.com/drive/folders/0B1K1m-YmE28DMGFrbmZZa0JjUWM?usp=sharing

passes Photon with no errors and warnings but gets rejected when submitted to Netflix.

The error message from the Netflix portal is "Found unexpected Index TableSegment LocalTag = 0x3f11"

The local tag 0x3f11 should be legal according "Amendment 2:2012 to SMPTE ST 377-1:2011"; page 9; 10 Index Table Layout.

Any advice?

Thanks

**Comment by svenkatrav** [comment] 2017-03-15 18:20
Sorry for the late reply. We will verify this behavior at our end and try to find root cause for this.

**Comment by svenkatrav** [comment] 2017-03-16 00:39
We have a issue in Photon parsing Index table with optional tags. The Photon IMP validation does not verify index tables where as Netflix ingestion relies on index tables and hence you are seeing this inconsistency. We have made changes in Photon to allow optional tags in index tables and also include index table validation in IMP analysis to keep consistency. Next release of Photon will include this fix.

**Comment by svenkatrav** [comment] 2017-06-23 20:38
Fix is included in v4.4.2.

**Closed by svenkatrav** 2017-06-23 20:38 UTC
